name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar JDK 17 (Eclipse Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar o Projeto
        run: mvn clean compile

      - name: Executar Testes Automatizados (JUnit)
        run: mvn test

      - name: Gerar Artefato (.jar)
        run: mvn package -DskipTests

      - name: Salvar Artefato de Build
        uses: actions/upload-artifact@v4
        with:
          name: java-api-package
          path: target/*.jar
